version: 1.0.{build}

image:
  - Visual Studio 2017

configuration:
  - Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\LLVM -> appveyor.yml

install:
  - cinst llvm
  - git submodule update --init --recursive

before_build:
  - msbuild /version
  - mkdir Build && cd Build
  - cmake ..

build:
  project: C:\projects\AnnotationGenerator\Build\ALL_BUILD.vcxproj
  verbosity: minimal
  parallel: true