version: 1.0.{build}

image:
  - Visual Studio 2017

environment:
  PYTHON: "C:\\Python27"
  REPOSITORY_KEY:
    secure: 3jorWUxqWjnR0X8Ye5NsAurPzickp84H2a+/ILwlRA3EQXzv+jo+kv9tvI1YKyTE

cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform: x64
configuration: Release

install:
  - git submodule update --init --recursive
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  # Conan
  - cmd: pip.exe install conan --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: pip.exe install conan_package_tools --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: refreshenv
  - cmd: conan user # It creates the conan data directory

build_script:
  - cmd: conan --version
  - cmd: conan create . bentoudev/yage -s build_type=Release -s arch=x86_64

on_success:
  - cmd: conan remote add yage https://api.bintray.com/conan/bentoudev/yage
  - cmd: conan user -p %REPOSITORY_KEY% -r yage bentoudev
  - cmd: conan upload Agnes/0.3@bentoudev/yage --all -r=yage