version: 1.0.{build}

image:
  - Visual Studio 2017

platform: x64
configuration: Release

install:
  - git submodule update --init --recursive

before_build:
  - msbuild /version
  - mkdir Build && cd Build
  - cmake -G="Visual Studio 15 2017 Win64" ..

build:
  project: C:\projects\AnnotationGenerator\Build\ALL_BUILD.vcxproj
  verbosity: minimal
  parallel: true