language: cpp

notifications:
  email: false

sudo: false
dist: trusty

services:
  - docker

secure: "TsniPN5EWc991q20yICwHli40b74UkFmtbPk5XBwGqQse4fh/LhX/yq29mKy3YrkOPCZhsk72lqlnatiaHb7XjG98kzrn29rOrfdnIs/3aAp+sr87wC5Tq8npB9Jg8CcKor5IihAy0E5IK40tSbZP6Zo66dd4oUTPg5SYdzdHHvGqCHsG6a9R/brEnJavfRoon1o5h5WeXclW+e6bKmeiP18RIE26Vb602ByI1BpYxkMKH2xQ5M0kMmyauI/5ZB3E/nj6/332DkOytzaRMq7HwQDFkrtzOCR68JMd1vt4w/ak14vHzjMzRzdAayCvNlChvAsShpN1zakIZBrdceqW3mYgJ6vxWkgssO/kdfl43xAQJTA7sJCEWMa5eIPKPVDCIEvc+ynjU1v/A2lFppCEvhTn2warGwrb42LU0J7Bqjm9L+ztGyEYpmDcQin3bpK1bd+uhLyTx6IQzTGLY8E1MvRy0vEaDEKvmfeC3T/ILbacbWcX1aqcExH+fQbZI55FJGympEelgz5gMWVQXIYnnvwgtUTKOQJWCLNoOSVUmQughWwVC50Dt5pN6i93inuR7eoDC9T1Qs11sNms1GkmvE6iSHxU2JNwJy0d3uFT/IZ2KqADtihJ8FJCDZL7TotVqXhmcUalJYwfAv1Pf+q8NMUTgWReAAvAMvnKasFtLI="

matrix:
  include:
    - os: linux
      compiler: clang-5
      script:
        - docker run --tty=false -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev sh ./build_clang.sh

before_script:
  - docker pull bentou/ubuntuartfuldev
  - docker ps -a
  - mkdir bin

after_success:
  - docker run -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev sh ./upload_travis.sh $REPOSITORY_KEY