language: cpp

notifications:
  email: false

sudo: false
dist: trusty
services:
  - docker

matrix:
  include:
  - os: linux
    compiler: clang-5
    script:
    - docker run --tty=false -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev -e "CI" -e "TRAVIS" -e "TRAVIS_TAG" sh ./build_clang.sh $REPOSITORY_KEY

before_script:
  - docker pull bentou/ubuntuartfuldev
  - docker ps -a
  - mkdir bin

env:
  global:
    secure: K+3gRXam4onbnTJkXz80qqQez3qUvtOhoBrYowFxtzhlOFtlnn9kdMQgvtvuAoPs/+Vv51ypFt8Xli+dtByalZ8jfTM4ucaVO8hFn61Tonx/P5XRyfYYgLcrH9aX4JUvpq1U6j9Kpw/0HyPyaFw9K+WmzT9cn+VlG4WvS/IDTefAoIpJm91GWPX/kKeP4VZtHfb9xuU4UI6CFL4Qh8LuPA3f9h2jcgpOSfgiKTRPRfu0+P7esMDAIq/Rxk66/ckQsxfU47kSt3Uyjp13wWhSkH14lkTCz2m3hsMxeOhbs6rbTC7qIiLjGk+WIG6YGCsq7ifN7Bt3Hkfp2gx0HJcPFM9mSYUqfhb9TMTmvaT6JparaRWmqJ+eji2zRLSDnBqO8/hLwECgfRhLTTkOdOpSRI//BfjomoHN9D8cDrFnfyc6HyW8hjjHw1nnScK67FTZBYv/E0xyg1xXb0HnZjxFQX2M/Csi+902eDN9N78QvelzIEDjagcFduqvFT4Ig5m4VjteE4iDKN0WZrKkJpqkNYM7FBMtdI8rQTUaq//zpGjv7l5j50vD9QY6KbhDpPJ4atgZAJZgESXvmD5Q+RZZWzi839/ApU3tpo0Sze1+9rb11SQgkkyiOvp1gliUckqIMv79q9CPUP8/D0qWcEX5UygZJlGRZxc5QI25jRve8Bc=
