language: cpp

notifications:
  email: false

sudo: false
dist: trusty

services:
  - docker

secure: pL86ZB5lKNsOutna6goLsAsduAs80kl9MU45PpjD0YjIk7T3IjISfnxFxHmb88kj1rLbRg9/kfXvVgmrkAwO5ZTzNDU1my+gFTUKsNHXK22S94j81OFwdkALyDFpV9m1xHSLvxYxQB5pEjik9qZbrlyeF+2IWgKeMVNGU0sc92MR/s56NpcIaUNKbODgu0MUROw/dYjXAYQUso5EKDtYOMM8ASzB/CeKen4EdFs5BivmTEdryVwcgLG8rUAEH+ZrI59m+UrrocTclbAYtdGkTA9lI9uuwXyPQwDz1n/G/3HGMOePdS8rkJN0sOdsrODCKxidvTZZD/CiyWC5MrYZb2jryIvw34cdEPwJYW5KlLZY9Zy6L+EEngttI2uSQ7F241ZhvFLqMwLafY1bdUFwq9/yUMHLje77lEdsuxgzFCdUzVDNwqn84ofAQB55Fq1l/xFGj3bZyIkmIdSfu6fespiNJCsAt61Cuz0aBCB8TP6LMvZbPWdktmLT6mmkQXj7yi8oYc170xOaSRJ1EKpzn5y9x8Qos3BQCM5dOayKH1gmd9CABYalpKYKTeokkXx1FQAYguITrWsAxXL1MZ9rplNkalMyRWgNSQCBiYHuR4EFhGQ7/LC9I4D8paLViOtLxmxboE6SuAs9gNuTXE9OqLeKmPqZ5Ge1CuTpGrljQEM=

matrix:
  include:
    - os: linux
      compiler: clang-5
      script:
        - docker run --tty=false -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev sh ./build_clang.sh

before_script:
  - docker pull bentou/ubuntuartfuldev
  - docker ps -a
  - mkdir bin
  
after_success:
  - docker run -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev $(conan remote add yage https://api.bintray.com/conan/bentoudev/yage && conan user -p $REPOSITORY_KEY -r yage bentoudev && conan upload Agnes/0.1@bentoudev/yage --all -r=yage)