language: cpp

notifications:
  email: false

sudo: false
dist: trusty

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: clang-5
      script:
        - docker run -it -v $PWD:/src --workdir /src bentou/ubuntuartfuldev sh ./build_clang.sh

before_script:
  - docker pull bentou/ubuntuartfuldev
  - docker ps -a
  - mkdir bin