# bumpver.toml
[bumpver]
current_version = "0.4.6"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "[bot] Bump version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"Source/Preprocessor/Utils/Version.h" = [
    'AGNES_VERSION = "{version}";',
]
"conanfile.py" = [
    "version = '{version}'",
]