project: AnnotationGenerator

config:
  verbose_build: false
  dev_profile: 'config/dev_profile.yml'
  platforms:
    - 'config/plat_windows.yml'
  rules:
    - 'config/msvc_rules.yml'
  configurations:
    - 'config/cfg_debug.yml'
    - 'config/cfg_develop.yml'
    - 'config/cfg_retail.yml'

conan:
  build_tools: build_tools.ini
  dependencies: dependencies.ini

targets:
  app:
   - 'Source/Preprocessor/project.yml'
  lib:
   - 'Source/LibClang/project.yml'
