target: 'Agnes'

config:
  kind: EXECUTABLE

dependencies:
  private:
    - libclang
    - Reflection
    - kainjow_mustache
    - nlohmann_json

source:
  paths: '.'
  patterns:
    - '*.cpp'

defines:
    private:
    - 'ANNOTATION_GENERATOR'
