name: CI (on push)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test_acceptance:
    uses: ./.github/workflows/test_acceptance.yml
    secrets: inherit
